[package]
name = "scalar_field"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.30.0"
ndarray = "0.15.4"
nalgebra = "0.29.0"
rand = "0.8.5"
isosurface = "0.0.4"
